
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry txtFolder;

	private global::Gtk.Button btnSelectFolder;

	private global::Gtk.Button btnScan;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.TreeView treeview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Select a folder to scan");
		this.hbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtFolder = new global::Gtk.Entry();
		this.txtFolder.CanFocus = true;
		this.txtFolder.Name = "txtFolder";
		this.txtFolder.IsEditable = true;
		this.txtFolder.InvisibleChar = '•';
		this.hbox1.Add(this.txtFolder);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtFolder]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSelectFolder = new global::Gtk.Button();
		this.btnSelectFolder.CanFocus = true;
		this.btnSelectFolder.Name = "btnSelectFolder";
		this.btnSelectFolder.UseStock = true;
		this.btnSelectFolder.UseUnderline = true;
		this.btnSelectFolder.Label = "gtk-open";
		this.hbox1.Add(this.btnSelectFolder);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSelectFolder]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnScan = new global::Gtk.Button();
		this.btnScan.CanFocus = true;
		this.btnScan.Name = "btnScan";
		this.btnScan.UseUnderline = true;
		this.btnScan.Label = global::Mono.Unix.Catalog.GetString("Scan");
		this.vbox1.Add(this.btnScan);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnScan]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.scrolledwindow1.Add(this.treeview1);
		this.vbox1.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
		w7.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnSelectFolder.Clicked += new global::System.EventHandler(this.OnSelectFolder);
		this.btnScan.Clicked += new global::System.EventHandler(this.OnScanFolder);
	}
}
